#!/bin/bash


if [ "$#" -lt 2 ]; then
  echo  "* Data and host:port not provided. Exiting."
  exit 1
fi

data=$1
host=$2

if [ "$#" -eq 3 ]; then
  puzzle=$3
else
  id=`curl -s -X GET http://$host/_uuids  | jq '.uuids[0]'`
  temp="${id%\"}"
  puzzle="${temp#\"}"
fi


curl -s -X PUT http://$host/puzzleservice/$puzzle -d @$data | jq .


