journeyservice:
  image: com.ibm.trek/journey-service:latest
  ports:
  - "8889:8889"
  links:
  - journeydb
  external_links:
  - zoo:zookeeper
  entrypoint: [
    "java", "-jar", "/app/journey-service.jar", "-port=8889",
    "-dbName=journeystore", "-dbHost=journeydb",
    "-zk=zk!zookeeper:2181!/finagle/journey!0"
  ]
journeydb:
  image: klaemo/couchdb:latest
  ports:
  - "5989:5984"
