playerservice:
  image: com.ibm.trek/player-service:latest
  ports:
  - "8888:8888"
  links:
  - playerdb
  external_links:
  - zoo:zookeeper
  entrypoint: [
    "java", "-jar", "/app/player-service.jar", "-port=8888",
    "-dbName=playerstore", "-dbHost=playerdb",
    "-zk=zk!zookeeper:2181!/finagle/player!0",
    "-journeyServer=zk!zookeeper:2181!/finagle/journey!0"
  ]
playerdb:
  image: klaemo/couchdb:latest
  ports:
  - "5981:5984"
