#!/bin/bash

# Generate javascript from the thrift definition files
thrift -r --gen js --o js thrift/puzzle-master-service-interface/PuzzleMasterService.thrift

echo "Open localhost:8000 in your browser to view your presentation"

python -m SimpleHTTPServer 8000


